---
title: "MBTA_LoadData"
author: "Marshall Thomas"
date: "September 29, 2017"
output: html_document
---
```{r echo=FALSE}
# Load libraries
library(jsonlite)
library(lubridate)
library(dplyr)
options(stringsAsFactors = FALSE)
```


```{r echo=FALSE}
# Function for queries from data API
URL_query = function(from,to,start_datetime,finish_datetime){
  start_time = as.integer(as.POSIXct((start_datetime), tz="America/New_York"))
  finish_time = as.integer(as.POSIXct((finish_datetime), tz="America/New_York"))
  url_start = "http://realtime.mbta.com/developer/api/v2.1/traveltimes?api_key="
  key = "wX9NwuHnZU2ToO7GmGR9uw"
  url_int = "&to_datetime="
  travel_times = read.csv(text="route_id,direction,dep_dt,arr_dt,travel_time_sec,benchmark_travel_time_sec,threshold_flag_1,threshold_flag_2,threshold_flag_3")

  while(start_time<finish_time){
    end = start_time + 86400
    request_url = paste(url_start, key, "&format=json&from_stop=", from, "&to_stop=", to,
    "&from_datetime=", start_time, "&to_datetime=", end, sep = "")
    dat = fromJSON(request_url)
    tt = dat$travel_times
    travel_times = bind_rows(travel_times, tt)
    start_time = end
  }

  travel_times$date = as.POSIXct(as.numeric(travel_times$dep_dt), 
                                 tz ="America/New_York", origin ="1970-01-01")
  travel_times$just_date = as.Date(travel_times$date, tz ="America/New_York")
  travel_times$time = strftime(travel_times$date, 
                               tz="America/New_York", format="%H:%M:%S")
  travel_times$day = weekdays(travel_times$just_date)
  return(travel_times)
}
```

```{r echo=FALSE}
if(!dir.exists("./TrainData/")){
  dir.create("./TrainData/")
}
#Queries for different train lines
start = "2016-07-01 00:00:00"
end = "2017-09-30 00:00:00"
# Orange line southbound (Oak Grove to Green Street)
orange_SB = URL_query("70036","70002", start, end)
write.csv(orange_SB, "./TrainData/OrangeLineSouthBound.csv")
# Orange line northbound (Forest Hills to Malden Center)
orange_NB = URL_query("70001","70035", start, end)
write.csv(orange_NB, "./TrainData/OrangeLineNorthBound.csv")
# Blue line westbound (Wonderland to Government Center)
blue_WB = URL_query("70060","70039", start, end)
write.csv(blue_WB, "./TrainData/BlueLineWestBound.csv")
# Blue line eastbound (Bowdoin to Revere Beach)
blue_EB = URL_query("70038","70058", start, end)
write.csv(blue_EB, "./TrainData/BlueLineEastBound.csv")
# Red line southbound to Ashmont (Alewife to Shawmut)
red_SB_Ash = URL_query("70061","70091", start, end)
write.csv(red_SB_Ash, "./TrainData/AshmontSouthBound.csv")
# Red line southbound to Braintree (Alewife to Quincy Adams)
red_SB_Brain = URL_query("70061","70103", start, end)
write.csv(red_SB_Brain, "./TrainData/BraintreeSouthBound.csv")
# Red line northbound from Ashmont (Ashmont to Davis)
red_NB_Ash = URL_query("70094","70064", start, end)
write.csv(red_NB_Ash, "./TrainData/AshmontNorthBound.csv")
# Red line northbound from Braintree (Braintree to Davis)
red_NB_Brain = URL_query("70105","70064", start, end)
write.csv(red_NB_Brain, "./TrainData/BraintreeNorthBound.csv")
```